### ISSUE TITLE
Is it possible to "skin" the swagger docs

### ISSUE THREAD

**Issue by aliuk2012** [ruby-grape/grape-swagger-rails#44] opened 2016-02-23 20:57 UTC
Hi,

Is there some way of setting up up Swagger Docs rails so it can use other methods in my application? 
Also I would like to reuse my default layout in app/views/layouts/application.html.haml, is this possible?

I do have swagger docs working and displaying but I would like to "skin" it to look like the rest of my application.

Many thanks

P.S relatively noobie rails developer

**Comment by dblock** [comment] 2016-02-24 11:57
If you want your layout and UI parts, for now you just have to port the interesting parts into your application, see https://github.com/artsy/doppler/blob/master/app/views/playground/index.html.haml for example.

**Comment by dblock** [comment] 2016-02-24 11:58
Closed as duplicate of https://github.com/ruby-grape/grape-swagger-rails/issues/27.

**Closed by dblock** 2016-02-24 11:57 UTC
