### ISSUE TITLE
grape-swagger compatibility

### ISSUE THREAD

**Issue by sunnyrjuneja** [ruby-grape/grape-swagger-rails#11] opened 2015-04-03 23:20 UTC
Hi,

I wanted to discuss the "out of the box" compatibility of grape-swagger and grape-swagger-rails. It seems that when you install grape-swagger-rails (0.1.0) while using grape (0.11.0) and grape-swagger (0.10.1), you need to set options that aren't obvious from the README.

The first error I encountered was that when you setup grape-swagger-rails, there is an flash of errors that override each other and end with:

`swagger_doc' from path http://api.rails-app.dev:3000/swagger_doc/swagger_doc.json (server returned undefined)`

The other flashed errors are the same message but `swagger_doc` replaced with your resource. From the rails log, I was able to see that it was requesting a resource that was suffixed with .json

```
Started GET "/swagger_doc/swagger_doc.json" for 127.0.0.1 at 2015-04-03 16:14:20 -0700

ActionController::RoutingError (No route matches [GET] "/swagger_doc/swagger_doc.json"):
````

But out of the box, grape-swagger only creates urls of the form (notice no .json):
`/swagger_doc/swagger_doc`

By changing 
`add_swagger_documentation`
to:

`add_swagger_documentation(format: :json)`

I was able to resolve the problem.

I propose that one or more of the following happens:

1. The README for grape-swagger is changed.
2. The README for grape-swagger-rails is changed.
3. The code in grape-swagger automatically assumes the format of `:json`.
4. Something better that the authors know. :)

I'm happy to send a PR anywhere for anything. I'm going to ping @dblock because he is so awesome and responds to everything grape related.

The following issues are relevant: 
https://github.com/tim-vandecasteele/grape-swagger/issues/190
https://github.com/tim-vandecasteele/grape-swagger/issues/197

**Comment by dblock** [comment] 2015-04-04 13:51
We discussed undoing the root cause of this in https://github.com/intridea/grape/issues/914, I think I would really like that, this has created such a mess.

Otherwise I think 3) is the way to go, ideally the default should be for a "typical" JSON API.

**Comment by TangMonk** [comment] 2015-04-08 09:37
same issue

the swagger-ui alert:

```
Unable to read api 'swagger_doc' from path http://localhost:3000/api/v1/swagger_doc.json/swagger_doc.json (server returned undefined)
```

`.json` suffix should only append to lasted path node

**Comment by dmitry** [comment] 2015-05-18 09:20
Looks like fix was merged, but still grape still not released with fix. `gem 'grape', github: 'intridea/grape'` works fine!

**Comment by aschuster3** [comment] 2016-05-21 18:52
Because this issue hasn't been updated in over a year, I'm assuming it was resolved or is now not relevant.  If this issue still exists in some form, please ping me here and I'll reopen it or open a new issue.

**Closed by aschuster3** 2016-05-21 18:52 UTC
Labels: new feature
